# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{light_mongo}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Elliot Crosby-McCullough"]
  s.date = %q{2010-03-30}
  s.description = %q{LightMongo is a lightweight Mongo object persistence layer for Ruby which makes use of Mongo's features rather than trying to emulate ActiveRecord.}
  s.email = %q{elliot.cm@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "integration/basic_storage_cycle_spec.rb",
     "integration/cross_collection_relationships_spec.rb",
     "integration/dynamic_finders_spec.rb",
     "integration/meta_spec.rb",
     "integration/object_embedding_spec.rb",
     "integration/support/integration_helper.rb",
     "lib/document.rb",
     "lib/document/persistence.rb",
     "lib/document/serialization.rb",
     "lib/document/serialization/hash_serializer.rb",
     "lib/document/serialization/serializer.rb",
     "lib/light_mongo.rb",
     "lib/util.rb",
     "spec/document/persistence_spec.rb",
     "spec/document/serialization/hash_serializer_spec.rb",
     "spec/document/serialization/serializer_spec.rb",
     "spec/document/serialization_spec.rb",
     "spec/document_spec.rb"
  ]
  s.homepage = %q{http://github.com/elliotcm/light_mongo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A lightweight Ruby object persistence library for Mongo DB}
  s.test_files = [
    "spec/document/persistence_spec.rb",
     "spec/document/serialization/hash_serializer_spec.rb",
     "spec/document/serialization/serializer_spec.rb",
     "spec/document/serialization_spec.rb",
     "spec/document_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

